In [26]:
import irreversible_stressstrain
reload(irreversible_stressstrain)

from irreversible_stressstrain import StressStrain as strainmodel

In [7]:
import graph_suite as plot
import material_analytics
import optimization_suite

model = strainmodel('ref/HSRS/22')

SS_stress=material_analytics.yield_stress(model.get_experimental_data())[0,1] # it's important to access yield_stress this way
plot.plotmult2D(model.get_experimental_data(),model.mcfunc((-100,1),SS_stress),marker2='r-')

863.845922326


## We must automatically determine yield stress, and then optimal parameters

In [8]:
model = strainmodel('ref/HSRS/22')
data = model.get_experimental_data()

"""[0,1] is the first row, second column, which is the stress values"""
SS_stress = material_analytics.yield_stress(data)[0,1]

print SS_stress

863.845922326


In [15]:
# -- testing to see if this will work still
from irreversible_stressstrain import StressStrain
from optimization_suite import minimize_suite as minim

stressmodel = StressStrain('ref/HSRS/222')
tominimize = stressmodel.mcfunc

# totally guessing min, all new data set
minim(tominimize, ['BFGS', 'L-BFGS-B','SLSQP'], [-500., 10.])

BFGS took 175.441886902 seconds. The result, 53.9904789232 was found at (-418.896972656, 10.0)
BFGS used 149.515625 megabytes and took 1.0 iterations

L-BFGS-B took 83.6906678677 seconds. The result, 48.5008678701 was found at (-319.851990106, 10.0)
L-BFGS-B used 149.62890625 megabytes and took 5.0 iterations

SLSQP took 119.519201994 seconds. The result, 48.5008678666 was found at (-319.849806339, 10.0)
SLSQP used 149.7578125 megabytes and took 12.0 iterations



In [16]:
# -- testing to see if this will work still
from irreversible_stressstrain import StressStrain
from optimization_suite import minimize_suite as minim

stressmodel = StressStrain('ref/HSRS/22')
tominimize = stressmodel.mcfunc

# totally guessing min, all new data set
minim(tominimize, ['L-BFGS-B',], [-500., 10.])

L-BFGS-B took 15.4999392033 seconds. The result, 459.719221261 was found at (-184.947948552, 10.0)
L-BFGS-B used 149.7578125 megabytes and took 3.0 iterations



## These are the results for ref/HSRS/22

In [38]:
stressmodel = StressStrain('ref/HSRS/22')
tominimize = stressmodel.mcfunc

# totally guessing min, all new data set
#minim(tominimize, ['L-BFGS-B',], [-100., 10.])

In [39]:
reload(plot)
plot.plotmult2D(stressmodel.get_experimental_data(),model.mcfunc((-185.092360586, 10.0)),marker2='r-')

IndexError: invalid index to scalar variable.

In [32]:
from irreversible_stressstrain import StressStrain as strainmodel
model = strainmodel('ref/HSRS/222')
data = model.get_experimental_data()

"""[0,1] is the first row, second column, which is the stress values"""
SS_stress = material_analytics.yield_stress(data)[0,1]

print SS_stress

1009.384532


In [28]:
reload(optimization_suite)
from optimization_suite import minimize_suite as minim
from irreversible_stressstrain import StressStrain as strainmodel

tominimize = model.mcfunc

minim(tominimize,,['L-BFGS-B',], [-500., 10.])

L-BFGS-B took 168.506247997 seconds. The result, 38.1879008562 was found at (-127613.815022, 10.0)
L-BFGS-B used 174.515625 megabytes and took 20.0 iterations



L-BFGS-B took 168.506247997 seconds. The result, 38.1879008562 was found at (-127613.815022, 10.0)
L-BFGS-B used 174.515625 megabytes and took 20.0 iterations

In [35]:
from irreversible_stressstrain import StressStrain as strainmodel
model = strainmodel('ref/HSRS/222')
data = model.get_experimental_data()

reload(plot)
plot.plotmult2D(data,model.mcfunc((-127613.815022, 10.0)),marker2='r-')

IndexError: invalid index to scalar variable.

In [52]:
import irreversible_stressstrain
reload(irreversible_stressstrain)

from irreversible_stressstrain import StressStrain as strainmodel
reload(optimization_suite)


model = strainmodel('ref/HSRS/22')
data = model.get_experimental_data()

"""[0,1] is the first row, second column, which is the stress values"""
SS_stress = material_analytics.yield_stress(data)[0,1]

"""If we pass in an SS_stress parameter, it returns the optimal model parameters"""
optimization_suite.minimize_suite(model.mcfunc, methods=['Nelder-Mead',], guess = [-150,1] ,SS_stress=SS_stress)

(-185.14371002406608, 1.510182934008961)

In [61]:
import irreversible_stressstrain
reload(irreversible_stressstrain)

from irreversible_stressstrain import StressStrain as strainmodel
reload(optimization_suite)


model = strainmodel('ref/HSRS/22')
data = model.get_experimental_data()

"""[0,1] is the first row, second column, which is the stress values"""
SS_stress = material_analytics.yield_stress(data)[0,1]

"""It returned the guess because it failed"""
model_params = optimization_suite.minimize_suite(model.mcfunc, methods=['BFGS',], guess = [-150,1] ,SS_stress=SS_stress)

In [60]:
import irreversible_stressstrain
reload(irreversible_stressstrain)
plot.plotmult2D(data, model.irreversible_model(model_params,SS_stress))

In [3]:
import irreversible_stressstrain
reload(irreversible_stressstrain)
import material_analytics
from irreversible_stressstrain import StressStrain as strainmodel

import optimization_suite
reload(optimization_suite)


model = strainmodel('ref/HSRS/22')
data = model.get_experimental_data()

"""[0,1] is the first row, second column, which is the stress values"""
SS_stress = material_analytics.yield_stress(data)[0,1]

"""If we pass in an SS_stress parameter, it returns the optimal model parameters"""
optimization_suite.minimize_suite(model.mcfunc, methods=['Nelder-Mead',], guess = [-150,1] ,SS_stress=SS_stress)

Nelder-Mead took 23.4551222324 seconds. The result, 459.589964579 was found at (-182.78840661, 0.9139529109)
Nelder-Mead used 81.953125 megabytes and took 30.0 iterations



material_analytics.py:327: RuntimeWarning: divide by zero encountered in log
  return a*np.log(x)+c
/site/x86/anaconda-1.8/anaconda/lib/python2.7/site-packages/scipy/optimize/minpack.py:690: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)


(-182.78840661048889, 0.91395291090011765)

# An example of how to use this in conjunction with irreversible thermodynamics model

In [6]:
import irreversible_stressstrain
reload(irreversible_stressstrain)

from irreversible_stressstrain import StressStrain as strainmodel
import optimization_suite
reload(optimization_suite)

import material_analytics
import graph_suite as plot


model = strainmodel('ref/HSRS/22')
data = model.get_experimental_data()

"""[0,1] is the first row, second column, which is the stress values"""
SS_stress = material_analytics.yield_stress(data)[0,1]

"""It returned the best fit"""
model_params = optimization_suite.minimize_suite(model.mcfunc, methods=['Nelder-Mead',], guess = [-150,1] ,SS_stress=SS_stress)

"""Plots the data versus the fitted data"""
plot.plotmult2D(data, model.irreversible_model(model_params,SS_stress))

Nelder-Mead took 24.801897049 seconds. The result, 459.589964579 was found at (-182.78840661, 0.9139529109)
Nelder-Mead used 139.6796875 megabytes and took 30.0 iterations



In [1]:
from irreversible_stressstrain import StressStrain as strainmodel
import optimization_suite
import material_analytics

model = strainmodel('ref/HSRS/22')
data = model.get_experimental_data()

SS_stress = material_analytics.yield_stress(data)[0,1]
model_params = optimization_suite.minimize_suite(model.mcfunc, methods=['Nelder-Mead',], guess = [-150,1] ,SS_stress=SS_stress)

material_analytics.py:331: RuntimeWarning: divide by zero encountered in log
  return a*np.log(x)+c
/site/x86/anaconda-1.8/anaconda/lib/python2.7/site-packages/scipy/optimize/minpack.py:690: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)


Nelder-Mead took 23.9607450962 seconds. The result, 459.589964579 was found at (-182.78840661, 0.9139529109)
Nelder-Mead used 114.01953125 megabytes and took 30.0 iterations

